### ISSUE TITLE
geodata library throws errors

### ISSUE THREAD

**Issue by C-F-K** [SURFnet/OpenOnderwijsAPI#14]
I followed the example setup instructions to the letter. Upon running `python manage.py syncdb` it threw the following error:

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/cameron/hackathon/OpenOnderwijsAPI/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/cameron/hackathon/OpenOnderwijsAPI/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/home/cameron/hackathon/OpenOnderwijsAPI/env/local/lib/python2.7/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/cameron/hackathon/OpenOnderwijsAPI/env/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/cameron/hackathon/OpenOnderwijsAPI/env/local/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/cameron/hackathon/OpenOnderwijsAPI/api/models.py", line 3, in <module>
    from haystack.utils.geo import Point
  File "/home/cameron/hackathon/OpenOnderwijsAPI/env/local/lib/python2.7/site-packages/haystack/utils/geo.py", line 2, in <module>
    from django.contrib.gis.geos import Point
ImportError: cannot import name Point
```

Changing the filename of point.py to Point.py solves this particular error, but throws a slew of new ones, such that the problem does not appear to be a simple typo in the `import` statement. (Which I felt obliged to make sure of before submitting an issue.)

I also feel obliged to point out that, barring the unlikely use-case that we need to send a GPS-guided missile at a specific UvA location, adding geodata to the API can in no conceivable circumstance be relevant, and therefore I am moved to question the wisdom of incorporating it.

**Comment by C-F-K** [comment]
This appears to be solved by doing `[sudo] apt-get install libgeos-dev`. However, `python manage.py syncdb` still throws errors:

```
System check identified some issues:

WARNINGS:
?: (1_6.W001) Some project unittests may not execute as expected.
	HINT: Django 1.6 introduced a new default test runner. It looks like this project was generated using Django 1.5 or earlier. You should ensure your tests are all running & behaving as expected. See https://docs.djangoproject.com/en/dev/releases/1.6/#new-test-runner for more information.
System check identified some issues:

WARNINGS:
?: (1_6.W001) Some project unittests may not execute as expected.
	HINT: Django 1.6 introduced a new default test runner. It looks like this project was generated using Django 1.5 or earlier. You should ensure your tests are all running & behaving as expected. See https://docs.djangoproject.com/en/dev/releases/1.6/#new-test-runner for more information.
Operations to perform:
  Synchronize unmigrated apps: oauth2, rest_framework_swagger, api, provider, rest_framework, haystack
  Apply all migrations: admin, contenttypes, sites, auth, sessions
Synchronizing apps without migrations:
  Creating tables...
  Installing custom SQL...
  Installing indexes...
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/cameron/hackathon/OpenOnderwijsAPI/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/cameron/hackathon/OpenOnderwijsAPI/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/cameron/hackathon/OpenOnderwijsAPI/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/cameron/hackathon/OpenOnderwijsAPI/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/cameron/hackathon/OpenOnderwijsAPI/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 533, in handle
    return self.handle_noargs(**options)
  File "/home/cameron/hackathon/OpenOnderwijsAPI/env/local/lib/python2.7/site-packages/django/core/management/commands/syncdb.py", line 27, in handle_noargs
    call_command("migrate", **options)
  File "/home/cameron/hackathon/OpenOnderwijsAPI/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 115, in call_command
    return klass.execute(*args, **defaults)
  File "/home/cameron/hackathon/OpenOnderwijsAPI/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/cameron/hackathon/OpenOnderwijsAPI/env/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 128, in handle
    created_models = self.sync_apps(connection, executor.loader.unmigrated_apps)
  File "/home/cameron/hackathon/OpenOnderwijsAPI/env/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 298, in sync_apps
    call_command('loaddata', 'initial_data', verbosity=self.verbosity, database=connection.alias, skip_validation=True, app_label=app_label, hide_empty=True)
  File "/home/cameron/hackathon/OpenOnderwijsAPI/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 115, in call_command
    return klass.execute(*args, **defaults)
  File "/home/cameron/hackathon/OpenOnderwijsAPI/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/cameron/hackathon/OpenOnderwijsAPI/env/local/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 61, in handle
    self.loaddata(fixture_labels)
  File "/home/cameron/hackathon/OpenOnderwijsAPI/env/local/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 91, in loaddata
    self.load_label(fixture_label)
  File "/home/cameron/hackathon/OpenOnderwijsAPI/env/local/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 148, in load_label
    obj.save(using=self.using)
  File "/home/cameron/hackathon/OpenOnderwijsAPI/env/local/lib/python2.7/site-packages/django/core/serializers/base.py", line 173, in save
    models.Model.save_base(self.object, using=using, raw=True)
  File "/home/cameron/hackathon/OpenOnderwijsAPI/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 626, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/home/cameron/hackathon/OpenOnderwijsAPI/env/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 198, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/cameron/hackathon/OpenOnderwijsAPI/env/local/lib/python2.7/site-packages/haystack/signals.py", line 48, in handle_save
    index.update_object(instance, using=using)
  File "/home/cameron/hackathon/OpenOnderwijsAPI/env/local/lib/python2.7/site-packages/haystack/indexes.py", line 277, in update_object
    backend.update(self, [instance])
  File "/home/cameron/hackathon/OpenOnderwijsAPI/env/local/lib/python2.7/site-packages/haystack/backends/elasticsearch_backend.py", line 187, in update
    bulk_index(self.conn, prepped_docs, index=self.index_name, doc_type='modelresult')
  File "/home/cameron/hackathon/OpenOnderwijsAPI/env/local/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 145, in bulk
    for ok, item in streaming_bulk(client, actions, **kwargs):
  File "/home/cameron/hackathon/OpenOnderwijsAPI/env/local/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 104, in streaming_bulk
    resp = client.bulk(bulk_actions, **kwargs)
  File "/home/cameron/hackathon/OpenOnderwijsAPI/env/local/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 68, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/cameron/hackathon/OpenOnderwijsAPI/env/local/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 712, in bulk
    params=params, body=self._bulk_body(body))
  File "/home/cameron/hackathon/OpenOnderwijsAPI/env/local/lib/python2.7/site-packages/elasticsearch/transport.py", line 301, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/home/cameron/hackathon/OpenOnderwijsAPI/env/local/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 78, in perform_request
    raise ConnectionError('N/A', str(e), e)
elasticsearch.exceptions.ConnectionError
```

My scepticism w.r.t. the inclusion of geodata stands.

**Comment by C-F-K** [comment]
Also this documentation is _awful_. There's no need for it to be in four different places. And _some_ mention of the fact that you need to install a totally isolated package (elasticsearch) and run it as a service, even just a link to their documentation, would stand a dangerously significant chance of making sense, which is, I presume, why this has been avoided.
